# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test_dev',
                'doc_host': 'https://mikejmills.github.io',
                'git_url': 'https://github.com/mikejmills/test_dev',
                'lib_path': 'test_dev'},
  'syms': { 'test_dev.core': { 'test_dev.core.HelloTensor': ('class_notebook.html#hellotensor', 'test_dev/core.py'),
                               'test_dev.core.HelloTensor.__init__': ('class_notebook.html#hellotensor.__init__', 'test_dev/core.py'),
                               'test_dev.core.HelloTensor.__repr__': ('class_notebook.html#hellotensor.__repr__', 'test_dev/core.py')}}}
