# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test_dev',
                'doc_host': 'https://mikejmills.github.io',
                'git_url': 'https://github.com/mikejmills/test_dev',
                'lib_path': 'test_dev'},
  'syms': { 'test_dev.class_notebook': { 'test_dev.class_notebook.HelloTensor': ( 'class_notebook.html#hellotensor',
                                                                                  'test_dev/class_notebook.py'),
                                         'test_dev.class_notebook.HelloTensor.__init__': ( 'class_notebook.html#hellotensor.__init__',
                                                                                           'test_dev/class_notebook.py'),
                                         'test_dev.class_notebook.HelloTensor.__repr__': ( 'class_notebook.html#hellotensor.__repr__',
                                                                                           'test_dev/class_notebook.py')},
            'test_dev.core': {'test_dev.core.say_hello': ('core.html#say_hello', 'test_dev/core.py')}}}
