# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/class_notebook.ipynb.

# %% auto 0
__all__ = ['HelloTensor']

# %% ../nbs/class_notebook.ipynb 3
class HelloTensor:
    def __init__(self, value: int):
        self.value = value
    def __repr__(self):
        return f"{self.value}"

